from pyrogram import filters
from pyrogram.types import Message
from shakky import app
from shakky.utils.database import get_weekly_stats
from shakky.utils.chart_gen import create_chart_card
from config import BANNED_USERS
import os

@app.on_message(filters.command(["charts", "weeklycharts"]) & filters.group & ~BANNED_USERS)
async def weekly_charts_command(client, message: Message):
    """
    Displays the weekly group chart as a beautiful image.
    """
    chat_id = message.chat.id
    mystic = await message.reply_text("📊 <b>Generating your Weekly Group Charts...</b>")
    
    stats = await get_weekly_stats(chat_id)
    if not stats or not stats.get("songs"):
        return await mystic.edit_text("➲ **No music history found for this week yet! Start playing to build your charts.**")
    
    # 1. Prepare Songs
    songs = stats.get("songs", {})
    top_songs = sorted(songs.items(), key=lambda x: x[1].get('count', 0), reverse=True)[:5]
    song_list = [(data.get('title', 'Unknown'), data.get('count', 0)) for vidid, data in top_songs]
    
    # 2. Prepare Users (Top DJ)
    users = stats.get("users", {})
    top_user_id = None
    if users:
        top_user_id = max(users.items(), key=lambda x: x[1].get('count', 0))[0]
    
    top_dj = "Unknown"
    if top_user_id:
        try:
            user = await client.get_users(int(top_user_id))
            top_dj = user.first_name
        except:
            top_dj = f"User({top_user_id})"
            
    # 3. Top Listener (Currently same as DJ in this logic, but we could separate if we had listener stats)
    top_listener = top_dj # Placeholder until we implement listener tracking
    
    # Generate Image
    try:
        image_path = create_chart_card(message.chat.title, song_list, top_dj, top_listener)
        await message.reply_photo(
            photo=image_path,
            caption=(
                f"<blockquote><b>🏆 WEEKLY GROUP CHARTS</b></blockquote>\n\n"
                f"➲ <b>Top DJ:</b> {top_dj}\n"
                f"➲ <b>Total Weekly Tracks:</b> <code>{sum(s[1] for s in song_list)}</code>\n\n"
                f"✧ *Generated by Shakky Premium Engine*"
            )
        )
        await mystic.delete()
        if os.path.exists(image_path):
            os.remove(image_path)
    except Exception as e:
        await mystic.edit_text(f"❌ <b>Error generating chart card:</b> `{e}`")
